pipeline {
  agent any
      options {
    buildDiscarder(logRotator(numToKeepStr: '5'))
  }
  environment {
    DOCKERHUB_CREDENTIALS = credentials('rihamm80-dockerhub')
        MYSQL_URI = credentials("MYSQL_URI")
        SECRET_KEY = credentials("SECRET_KEY")
	MYSQL_USER= 'root'
	MYSQL_URL = 'mysql'
	MYSQL_DATABASE = 'library'
	MYSQL_PASSWORD = credentials("MYSQL_PASSWORD")
	MYSQL_TEST = credentials("MYSQL_TEST")
  }
  stages {
      
    stage('Build') {
      steps {
        sh 'docker build -t riham80/mysql-5.7:latest db'
	    sh 'docker build -t riham80/flask-app:latest flask-app '
 
      }
    }
    stage('Test') {
       steps {
          sh ' bash test.sh  '
          sh ' echo testing'
           }
       }

    stage('RUN') {
      steps {
	      sshagent(credentials:['019a24ec-56e5-4bc3-8926-3584ab2cdbd1']){
           sh ' docker stack deploy --compose-file docker-compose.yaml stack1 '
        }
      }
    }
    stage('Push') {
       steps {
          sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
          sh ' docker push riham80/mysql-5.7:latest'
          sh ' docker push riham80/flask-app:latest'
           }
       } 
    

  } //stages
  post {
    always {
	junit 'junit_report.xml'
        cobertura autoUpdateHealth: false, autoUpdateStability: false, coberturaReportFile: 'coverage.xml', conditionalCoverageTargets: '70, 0, 0', failUnhealthy: false, failUnstable: false, lineCoverageTargets: '80, 0, 0', maxNumberOfBuilds: 0, methodCoverageTargets: '80, 0, 0', onlyStable: false, sourceEncoding: 'ASCII', zoomCoverageChart: false
      
    }
  }

} //pipeline
